### ISSUE TITLE
Refactor class interrupts into generic function

### ISSUE THREAD

**Issue by ejt1** [TeamWector/Pallas#42]
Right now most class behaviors have some sort of interrupt function laying around, merge these into a generic interrupt function instead.

https://github.com/TeamWector/Pallas/blob/master/behaviors/wow_retail/demonhunter/common.lua#L25
https://github.com/TeamWector/Pallas/blob/master/behaviors/wow_retail/mage/common.lua#L25
https://github.com/TeamWector/Pallas/blob/master/behaviors/wow_retail/warrior/common.lua#L70
https://github.com/TeamWector/Pallas/blob/master/behaviors/wow_wrath/deathknight/common.lua#L265

etc

**Comment by SovietFarmer** [comment]
Not touching Wrath, because cannot test, diff account for retail, other one is asleep. Fixed for DH/Mage/Sham/Huntard/Monk/Pal. Leaving Warrior retail for @ejt1.
