### ISSUE TITLE
Add support for PvP (Players) Combat Targetting.

### ISSUE THREAD

**Issue by NeerOC** [TeamWector/Pallas#45]
**Currently the Combat targetting system does not account for players you are in combat with or PvP in general.**
Let's add another list to populate with, currently we have:
_Combat.Targets_

I suggest we also add:
_Combat.Players_ 

This will minimize the requirements for custom PvP loops since we are already looping huge unit lists inside our targeting system.

**Comment by ejt1** [comment]
It should already include player targets, you can look at https://github.com/TeamWector/Pallas/blob/master/system/combat.lua#L50 where it collects all objects matching the flag `Unit` which includes active player, players and units.
